CREATE TABLE schedules(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    userid INTEGER REFERENCES users(id),
    startMon timestamp DEFAULT NULL,
    endMon timestamp DEFAULT NULL,
    startTues timestamp DEFAULT NULL,
    endTues timestamp DEFAULT NULL,
    startWed timestamp DEFAULT NULL,
    endWed timestamp DEFAULT NULL,
    startThurs timestamp DEFAULT NULL,
    endThurs timestamp DEFAULT NULL,
    startFri timestamp DEFAULT NULL,
    endFri timestamp DEFAULT NULL,
    startSat timestamp DEFAULT NULL,
    endSat timestamp DEFAULT NULL,
    startSun timestamp DEFAULT NULL,
    endSun timestamp DEFAULT NULL
);